export const translations = {
  TR: {
    assistantwelcome: "Yemek Asistanınız",
    assistantTitle: "Sanal Asistanınız",
    greeting: "Selamlar. :)",
    greeting2: "Size nasıl yardımcı olabilirim?",
    pageTitle: "Türk Hava Yolları",
    mainpagetitle: "Menu Assistant",
    mainpagedescription:
      "Please upload the photo or PDF version of the menu you would like assistance with.",
    mainpageclick: "Please Click Here",
    mainpagesend: "Upload",
    overlaymessage: "Sizin için menünüzü inceliyoruz. Az sonra hazırız.",
    kalori: "Kalori",
    vegan: "Vegan",
    gluten: "Gluten",
    alerjen: "Alerjen",
    evet: "Evet",
    hayir: "Hayır",
    initparams:
      "Sen bir yemek uzmanısın. Kullanıcıya menü analizi ve yemek önerileri hakkında yardımcı ol. Sadece menünün analizi ve yemekler ile ilgili cevaplar ver. Bağlam dışında hiç bir konuya kesinlikle cevap verme. Hangi dilde yazılırsa o dilde cevap ver",
    responselanguage: ". Türkçe dilinde cevap ver.",
  },
  GB: {
    assistantwelcome: "Food Chatbot",
    assistantTitle: "Virtual Assistant",
    greeting: "Hello! :)",
    greeting2: "How can I help you today?",
    mainpagetitle: "Menu Assistant",
    mainpagedescription:
      "Please upload the photo or PDF version of the menu you would like assistance with.",
    mainpageclick: "Please Click Here",
    mainpagesend: "Upload",
    overlaymessage: "Reviewing menu for you. We'll be ready shortly.",
    kalori: "Calories",
    vegan: "Vegan",
    gluten: "Gluten",
    alerjen: "Allergen",
    evet: "Yes",
    hayir: "No",
    initparams:
      "You are a culinary expert. Assist the user with menu analysis and food recommendations. Only respond to questions related to menu analysis and food recommendations. Do not answer questions outside this context. Respond in the same language as the user's input.",
    responselanguage: ". İngilizce dilinde cevap ver.",
  },
};
